"use client"

// Icon set for the Comercial module — design icon names mapped to lucide-react.
// v2 (Comercial v2 handoff) added the Cx-kit names: calendarClock, fileCheck,
// thumbs, sunrise, wifiOff, kanban, sliders, layoutGrid, send, repeat, etc.
import {
  AlertCircle,
  AlertTriangle,
  ArrowRight,
  BarChart,
  Banknote,
  Building2,
  Calendar,
  CalendarClock,
  Check,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  CircleDot,
  Clock,
  Code,
  Coins,
  Copy,
  Download,
  Eye,
  FileCheck2,
  FileText,
  Filter,
  Flame,
  GitMerge,
  Home,
  Inbox,
  Kanban,
  LayoutGrid,
  Link2,
  List,
  type LucideIcon,
  Mail,
  Megaphone,
  MessageCircle,
  Minus,
  MinusCircle,
  MoreHorizontal,
  MousePointerClick,
  Paperclip,
  Pencil,
  Phone,
  Percent,
  PieChart,
  Plus,
  Receipt,
  RefreshCw,
  Repeat,
  Scale,
  Search,
  Send,
  SlidersHorizontal,
  Sparkles,
  Sunrise,
  Target,
  ThumbsDown,
  ThumbsUp,
  Trash2,
  TrendingDown,
  TrendingUp,
  Upload,
  User,
  UserPlus,
  Users,
  Wallet,
  WifiOff,
  X,
  Zap,
} from "lucide-react"

const ICONS = {
  home: Home,
  funnel: Filter,
  filter: Filter,
  megaphone: Megaphone,
  users: Users,
  download: Download,
  coins: Coins,
  userPlus: UserPlus,
  plus: Plus,
  trendingUp: TrendingUp,
  trendingDown: TrendingDown,
  handshake: CheckCircle2,
  gitMerge: GitMerge,
  percent: Percent,
  target: Target,
  user: User,
  mousePointerClick: MousePointerClick,
  receipt: Receipt,
  banknote: Banknote,
  arrowRight: ArrowRight,
  alertTriangle: AlertTriangle,
  alertCircle: AlertCircle,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  chevronDown: ChevronDown,
  x: X,
  inbox: Inbox,
  calendar: Calendar,
  calendarClock: CalendarClock,
  search: Search,
  upload: Upload,
  history: Clock,
  clock: Clock,
  fileSpreadsheet: FileText,
  fileCheck: FileCheck2,
  fileText: FileText,
  braces: Code,
  barChart: BarChart,
  pieChart: PieChart,
  sparkles: Sparkles,
  copy: Copy,
  check: Check,
  checkCircle: CheckCircle2,
  edit: Pencil,
  refreshCw: RefreshCw,
  repeat: Repeat,
  moreHorizontal: MoreHorizontal,
  wallet: Wallet,
  paperclip: Paperclip,
  messageCircle: MessageCircle,
  phone: Phone,
  mail: Mail,
  send: Send,
  thumbsUp: ThumbsUp,
  thumbsDown: ThumbsDown,
  minusCircle: MinusCircle,
  minus: Minus,
  sunrise: Sunrise,
  wifiOff: WifiOff,
  flame: Flame,
  kanban: Kanban,
  list: List,
  sliders: SlidersHorizontal,
  layoutGrid: LayoutGrid,
  circleDot: CircleDot,
  link2: Link2,
  trash2: Trash2,
  building: Building2,
  eye: Eye,
  scale: Scale,
  zap: Zap,
} satisfies Record<string, LucideIcon>

export type CmIconName = keyof typeof ICONS

export function Icon({
  name,
  size = 15,
  strokeWidth = 1.9,
  className,
  style,
}: {
  name: CmIconName
  size?: number
  strokeWidth?: number
  className?: string
  style?: React.CSSProperties
}) {
  const C = ICONS[name]
  return <C size={size} strokeWidth={strokeWidth} className={className} style={style} />
}
