import { createGlobalThemeContract } from "@vanilla-extract/css";

export const tokens = createGlobalThemeContract({
  brand: {
    navy: "brand-navy",
    gold: "brand-gold",
    goldSoft: "brand-gold-soft",
    goldDeep: "brand-gold-deep",
  },
  font: {
    sans: "font-sans",
    display: "font-display",
    mono: "font-mono",
  },
  radius: {
    xs: "r-xs",
    sm: "r-sm",
    md: "r-md",
    lg: "r-lg",
    xl: "r-xl",
    "2xl": "r-2xl",
  },
  space: {
    "1": "s-1",
    "2": "s-2",
    "3": "s-3",
    "4": "s-4",
    "5": "s-5",
    "6": "s-6",
    "7": "s-7",
    "8": "s-8",
    "9": "s-9",
    "10": "s-10",
  },
  color: {
    bg: "bg",
    bgElevated: "bg-elevated",
    bgSunken: "bg-sunken",
    bgSoft: "bg-soft",
    surface: "surface",
    surfaceHover: "surface-hover",
    border: "border",
    borderStrong: "border-strong",
    text: "text",
    textMuted: "text-muted",
    textSubtle: "text-subtle",
    accent: "accent",
    accentSoft: "accent-soft",
    shadowSm: "shadow-sm",
    shadowMd: "shadow-md",
    shadowLg: "shadow-lg",
    ring: "ring",
  },
});
