"use client"

// Icon set for the Tarefas module — design icon names mapped to lucide-react.
import {
  AlertCircle,
  AlertTriangle,
  Archive,
  ArrowRight,
  AtSign,
  BarChart3,
  Bell,
  Briefcase,
  Building2,
  Calendar,
  CalendarCheck,
  CalendarClock,
  CalendarRange,
  Check,
  CheckCircle2,
  CheckSquare,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  CircleDot,
  Clock,
  Copy,
  Eye,
  EyeOff,
  FileCheck2,
  FileText,
  Flag,
  Flame,
  Folder,
  Funnel,
  Gavel,
  GripVertical,
  Handshake,
  Inbox,
  Kanban,
  LayoutGrid,
  Link2,
  List,
  ListChecks,
  ListTodo,
  type LucideIcon,
  MessageSquare,
  Mic,
  MicOff,
  Moon,
  MoreHorizontal,
  Paperclip,
  Pencil,
  Plus,
  RefreshCw,
  Repeat,
  Scale,
  Search,
  SlidersHorizontal,
  Sparkles,
  Star,
  Sun,
  Sunrise,
  Target,
  Trash2,
  User,
  UserPlus,
  Users,
  X,
} from "lucide-react"

const ICONS = {
  plus: Plus,
  calendar: Calendar,
  calendarClock: CalendarClock,
  calendarDay: CalendarCheck,
  calendarRange: CalendarRange,
  archive: Archive,
  mic: Mic,
  micOff: MicOff,
  paperclip: Paperclip,
  sliders: SlidersHorizontal,
  sunrise: Sunrise,
  target: Target,
  flag: Flag,
  flame: Flame,
  sparkles: Sparkles,
  listChecks: ListChecks,
  listTodo: ListTodo,
  check: Check,
  checkCircle: CheckCircle2,
  chevronDown: ChevronDown,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  chevronUp: ChevronUp,
  layoutGrid: LayoutGrid,
  user: User,
  inbox: Inbox,
  sun: Sun,
  moon: Moon,
  list: List,
  kanban: Kanban,
  repeat: Repeat,
  bell: Bell,
  atSign: AtSign,
  messageSquare: MessageSquare,
  gripVertical: GripVertical,
  briefcase: Briefcase,
  gavel: Gavel,
  x: X,
  link2: Link2,
  fileText: FileText,
  trash2: Trash2,
  circleDot: CircleDot,
  funnel: Funnel,
  building: Building2,
  handshake: Handshake,
  scale: Scale,
  fileCheck: FileCheck2,
  userPlus: UserPlus,
  folder: Folder,
  barChart: BarChart3,
  copy: Copy,
  star: Star,
  search: Search,
  users: Users,
  eye: Eye,
  eyeOff: EyeOff,
  edit: Pencil,
  moreHorizontal: MoreHorizontal,
  refreshCw: RefreshCw,
  alertTriangle: AlertTriangle,
  alertCircle: AlertCircle,
  checkSquare: CheckSquare,
  arrowRight: ArrowRight,
  clock: Clock,
} satisfies Record<string, LucideIcon>

export type TfIconName = keyof typeof ICONS

export function Icon({
  name,
  size = 15,
  strokeWidth = 1.9,
  className,
  style,
}: {
  name: TfIconName
  size?: number
  strokeWidth?: number
  className?: string
  style?: React.CSSProperties
}) {
  const C = ICONS[name]
  return <C size={size} strokeWidth={strokeWidth} className={className} style={style} />
}
