"use client"

// Icon set for the CRM module — the design's icon names mapped to lucide-react.
// Superset of every name referenced across the ported CRM components. Unknown
// names fall back to CircleDot so a missing mapping degrades gracefully instead
// of crashing. Mirrors comercial/cm-icons.tsx.
import {
  AlertCircle,
  AlertTriangle,
  ArrowDownRight,
  ArrowRight,
  ArrowRightCircle,
  ArrowUpRight,
  AtSign,
  Banknote,
  BarChart3,
  Bell,
  Braces,
  Briefcase,
  Building2,
  Calendar,
  CalendarClock,
  Check,
  CheckCircle2,
  CheckSquare,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  CircleDot,
  Clock,
  Coins,
  Copy,
  CornerDownRight,
  Download,
  ExternalLink,
  Eye,
  Feather,
  FileCheck2,
  FileSpreadsheet,
  FileText,
  Filter,
  Flag,
  Flame,
  Folder,
  Gavel,
  Globe,
  GripVertical,
  Handshake,
  History,
  Home,
  Inbox,
  LayoutGrid,
  Link2,
  List,
  ListChecks,
  LogOut,
  type LucideIcon,
  Mail,
  MapPin,
  Megaphone,
  Menu,
  Mic,
  Minus,
  MinusCircle,
  Moon,
  MoreHorizontal,
  MousePointerClick,
  PanelLeft,
  Paperclip,
  Pencil,
  PencilLine,
  Percent,
  Phone,
  PieChart,
  Plus,
  Receipt,
  RefreshCw,
  Repeat,
  Scale,
  Scroll,
  Search,
  Send,
  Settings,
  Sigma,
  SlidersHorizontal,
  Sparkles,
  Star,
  Sun,
  Sunrise,
  Target,
  ThumbsDown,
  ThumbsUp,
  Trash2,
  TrendingDown,
  TrendingUp,
  Upload,
  User,
  UserPlus,
  Users,
  Wallet,
  Wand2,
  WifiOff,
  X,
  Zap,
} from "lucide-react"

const ICONS = {
  fileText: FileText,
  scroll: Scroll,
  handshake: Handshake,
  gavel: Gavel,
  scale: Scale,
  sparkles: Sparkles,
  wand: Wand2,
  edit: Pencil,
  send: Send,
  download: Download,
  eye: Eye,
  history: History,
  home: Home,
  folder: Folder,
  users: Users,
  briefcase: Briefcase,
  settings: Settings,
  search: Search,
  plus: Plus,
  chevronRight: ChevronRight,
  chevronLeft: ChevronLeft,
  chevronDown: ChevronDown,
  arrowRight: ArrowRight,
  check: Check,
  checkCircle: CheckCircle2,
  paperclip: Paperclip,
  menu: Menu,
  sidebar: PanelLeft,
  sun: Sun,
  moon: Moon,
  bell: Bell,
  filter: Filter,
  moreHorizontal: MoreHorizontal,
  mic: Mic,
  copy: Copy,
  star: Star,
  building: Building2,
  user: User,
  calendar: Calendar,
  mail: Mail,
  fileCheck: FileCheck2,
  sliders: SlidersHorizontal,
  sigma: Sigma,
  logout: LogOut,
  circleDot: CircleDot,
  feather: Feather,
  wallet: Wallet,
  receipt: Receipt,
  trendingUp: TrendingUp,
  trendingDown: TrendingDown,
  arrowUpRight: ArrowUpRight,
  arrowDownRight: ArrowDownRight,
  alertTriangle: AlertTriangle,
  alertCircle: AlertCircle,
  clock: Clock,
  refreshCw: RefreshCw,
  upload: Upload,
  target: Target,
  externalLink: ExternalLink,
  banknote: Banknote,
  pieChart: PieChart,
  arrowRightCircle: ArrowRightCircle,
  zap: Zap,
  minusCircle: MinusCircle,
  phone: Phone,
  mapPin: MapPin,
  flag: Flag,
  inbox: Inbox,
  list: List,
  kanban: LayoutGrid,
  repeat: Repeat,
  gripVertical: GripVertical,
  listChecks: ListChecks,
  checkSquare: CheckSquare,
  cornerDownRight: CornerDownRight,
  link2: Link2,
  globe: Globe,
  calendarClock: CalendarClock,
  x: X,
  layoutGrid: LayoutGrid,
  flame: Flame,
  trash2: Trash2,
  sunrise: Sunrise,
  megaphone: Megaphone,
  userPlus: UserPlus,
  barChart: BarChart3,
  percent: Percent,
  coins: Coins,
  mousePointerClick: MousePointerClick,
  funnel: Filter,
  fileSpreadsheet: FileSpreadsheet,
  braces: Braces,
  thumbsUp: ThumbsUp,
  thumbsDown: ThumbsDown,
  wifiOff: WifiOff,
  at: AtSign,
  edit3: PencilLine,
  minus: Minus,
} satisfies Record<string, LucideIcon>

export type CrmIconName = keyof typeof ICONS

export function Icon({
  name,
  size = 15,
  strokeWidth = 1.9,
  className,
  style,
}: {
  name: CrmIconName | string
  size?: number
  strokeWidth?: number
  className?: string
  style?: React.CSSProperties
}) {
  const C = (ICONS as Record<string, LucideIcon>)[name] ?? CircleDot
  return <C size={size} strokeWidth={strokeWidth} className={className} style={style} />
}
